.PHONY: clean All

All:
	@echo "----------Building project:[ 03_Enums - Debug ]----------"
	@cd "03_Enums" && "$(MAKE)" -f  "03_Enums.mk"
clean:
	@echo "----------Cleaning project:[ 03_Enums - Debug ]----------"
	@cd "03_Enums" && "$(MAKE)" -f  "03_Enums.mk" clean
