.PHONY: clean All

All:
	@echo "----------Building project:[ 03_MultiDimensionArrays - Debug ]----------"
	@cd "03_MultiDimensionArrays" && "$(MAKE)" -f  "03_MultiDimensionArrays.mk"
clean:
	@echo "----------Cleaning project:[ 03_MultiDimensionArrays - Debug ]----------"
	@cd "03_MultiDimensionArrays" && "$(MAKE)" -f  "03_MultiDimensionArrays.mk" clean
