.PHONY: clean All

All:
	@echo "----------Building project:[ 02_Calc - Debug ]----------"
	@cd "02_Calc" && "$(MAKE)" -f  "02_Calc.mk"
clean:
	@echo "----------Cleaning project:[ 02_Calc - Debug ]----------"
	@cd "02_Calc" && "$(MAKE)" -f  "02_Calc.mk" clean
