.PHONY: clean All

All:
	@echo "----------Building project:[ 03_StringsAndAddresses - Debug ]----------"
	@cd "03_StringsAndAddresses" && "$(MAKE)" -f  "03_StringsAndAddresses.mk"
clean:
	@echo "----------Cleaning project:[ 03_StringsAndAddresses - Debug ]----------"
	@cd "03_StringsAndAddresses" && "$(MAKE)" -f  "03_StringsAndAddresses.mk" clean
