.PHONY: clean All

All:
	@echo "----------Building project:[ 05_StringFunctions - Debug ]----------"
	@cd "05_StringFunctions" && "$(MAKE)" -f  "05_StringFunctions.mk"
clean:
	@echo "----------Cleaning project:[ 05_StringFunctions - Debug ]----------"
	@cd "05_StringFunctions" && "$(MAKE)" -f  "05_StringFunctions.mk" clean
